{% set name = "cornac" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: ada6d09bd78bbd5b7cd65d2eb8599146e4b8f52ef44651cb25fa6a019d36aa56
  - url: https://github.com/PreferredAI/cornac/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 1a4b9839ce6e697155c3ef1b4d85d582a316cef93f24e7157e9275422e021e9b
    folder: gh_src

build:
  skip: True  # [py<38 or py>312]
  number: 0
  script:
    # https://github.com/PreferredAI/cornac/blob/v2.2.2/setup.py#L328
    # - {{ PYTHON }} setup.py build_ext -j{{ CPU_COUNT }}
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx and arm64]
  host:
    - llvm-openmp  # [osx and arm64]
    - python
    - pip
    - cython
    - numpy {{ numpy }}
    # some models cimports scipy.linalg.cython_blas
    - scipy 1.10.1 # [py<312]
    - scipy 1.11   # [py==312]
    - wheel
    - setuptools
    - libgomp  # [linux]
  run:
    - llvm-openmp  # [osx and arm64]
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scipy') }}
    # add furher pinnings for numpy and scipy
    - numpy <2.0.0
    - scipy <=1.13.1
    - libgomp  # [linux]
    - tqdm
    - powerlaw

test:
  imports:
    - cornac
  requires:
    - pip
    - pytest
    # - pytest-pep8 # unavailable
    - pytest-xdist
    # required to test the models (not mentioned in the requirements)
    - flask
  source_files:
    - gh_src/tests
    - gh_src/pytest.ini
  commands:
    - pip check
    - cd gh_src
    - pytest -vv tests

about:
  home: https://cornac.preferred.ai/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: A Comparative Framework for Multimodal Recommender Systems
  description: |
    Cornac is a comparative framework for multimodal recommender systems.
    Cornac enables fast experiments and straightforward implementations of new models.
    It is highly compatible with existing machine learning libraries (e.g., TensorFlow, PyTorch).
  doc_url: https://cornac.readthedocs.io
  dev_url: https://github.com/PreferredAI/cornac

extra:
  recipe-maintainers:
    - tqtg
