{% set name = "cornac" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 6253d932c7fd65126c3be948134e5d04ecb756f7bf79a081ec0e32dc0dd1df39
  # for upstream tests and their pytest.ini
  - url: https://github.com/PreferredAI/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 84aaac09e6a198700a8450681c67087cbe3aeaa4b37d3419b323ae09f0d97621
    folder: gh_src

build:
  skip: true  # [py<39]
  number: 0
  script:
    # build extra modules
    # https://github.com/PreferredAI/cornac/blob/v2.3.3/setup.py#
    - {{ PYTHON }} setup.py build_ext -j{{ CPU_COUNT }}
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  ignore_run_exports:
    - numpy
    - libgomp      # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - llvm-openmp 14.0.6 # [osx and arm64]
    - python
    - pip
    - setuptools >=42
    - wheel
    - cython >=0.29.21
    - numpy {{ numpy }}
    # We now require a numpy 2.[01] compatible scipy, ie >=1.13.1=*_1
    - scipy 1.13.1      # [py<313]
    - scipy 1.14.1      # [py>=313]
    # libgomp isn't obvious but you'll get an overdepending error
    # against cpython .so files without it
    - libgomp 11.2.0    # [linux]
  run:
    - llvm-openmp # [osx and arm64]
    - python
    # add further pinnings for numpy and scipy
    - numpy >2.0.0
    - scipy
    - libgomp     # [linux]
    - tqdm
    - powerlaw

test:
  imports:
    - cornac
  requires:
    - pip
    - pytest
    - pytest-xdist
    # flask required to test the models (not mentioned
    # in the requirements, but in the tests)
    - flask
  source_files:
    - gh_src/tests
    - gh_src/pytest.ini
  commands:
    - pip check
    - cd gh_src
    - pytest -vv tests

about:
  home: https://cornac.preferred.ai/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: A Comparative Framework for Multimodal Recommender Systems
  description: |
    Cornac is a comparative framework for multimodal recommender systems.
    Cornac enables fast experiments and straightforward implementations of new models.
    It is highly compatible with existing machine learning libraries (e.g., TensorFlow, PyTorch).
  doc_url: https://cornac.readthedocs.io
  dev_url: https://github.com/PreferredAI/cornac

extra:
  recipe-maintainers:
    - tqtg
