{% set name = "cornac" %}
{% set version = "2.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PreferredAI/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8211143def7cbd09689ff3fc853228172a08bc60610032e8391c74a891ef1ed8

build:
  number: 0
  script:
    # build extra modules
    # https://github.com/PreferredAI/cornac/blob/v2.3.5/setup.py#
    - {{ PYTHON }} setup.py build_ext -j{{ CPU_COUNT }}
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=42
    - wheel
    - cython >=0.29.21
    - numpy {{ numpy }}
    - scipy
    - libgomp 14.3.0    # [linux]
    - llvm-openmp 20.1.8 # [osx and arm64]
  run:
    - python
    # add further pinnings for numpy and scipy
    - numpy >2.0.0
    - scipy
    - tqdm
    - powerlaw
    - libgomp     # [linux]
    - llvm-openmp # [osx and arm64]
test:
  source_files:
    - tests
    - pytest.ini
  imports:
    - cornac
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest
    - pytest-xdist
    - flask

about:
  home: https://cornac.preferred.ai
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: A Comparative Framework for Multimodal Recommender Systems
  description: |
    Cornac is a comparative framework for multimodal recommender systems.
    Cornac enables fast experiments and straightforward implementations of new models.
    It is highly compatible with existing machine learning libraries (e.g., TensorFlow, PyTorch).
  doc_url: https://cornac.readthedocs.io
  dev_url: https://github.com/PreferredAI/cornac

extra:
  recipe-maintainers:
    - tqtg
