travis:
  secure:
    BINSTAR_TOKEN: drPPktg0nQQsFL8JTorUGej7JkvIpffAx5BF+7OdyTYVPIR8Bv4XjhnmeXIutL/n4mHe+Pd8AhXWLBnUTFM6JrZen0rRitcLRY4fWbpVppbF00cet7H4zJC69S8EiswnOOLzbneh6EIsxI+QSzRBhR81lD8mdMZuSiTbr2EU5eJG0zSw3QnsR3p8+e3tWS6Tf7vJQ3sIm19JF6lz52DWQV1qO+uwaWCSBnLzWpnNsH5TemywQn9zX1VA8lbNA0nG0qOdEVJFtwhtIxvkM2JntYeoqQInNruLdBbkWhbXG/RPcYSsn+1Lxk+O8RZCHTKk3B9OWFmNlTDXlIJe31Lsfl37mgbyIMFbD+4B6GwT8zglINfJfxF+giEuUSWHkiwNxTiH6KTR6EOgVZPwrpZwafNvP1OKZ+8/2CLUVQeLWQ9vqG5+XOF+n7FV6zS6+nsuVYqCSmwcdniZo0i3PCMj4kEcMqoHhsc++JDbHYi1XW+B8uSGFq6hRT0HY9RXb6Ak4XD7Nu98MMBgM290k/tvo2afO42ZEutLitm9OvDSaXYuk8QyBMbK4f4UXJaCH/e5tnbKj4EPk3r0bpF/2NDaN6aMZEzkkVJvpfuXqnBtSPjKKjIolRvzHw6kMLuqHo6F4xLeXw/5jD1vT6twJBougwVgReDVv3pWjTknxBHbuv0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
