travis:
  secure:
    BINSTAR_TOKEN: bnJbAd4vbv4S8L9jO4NlEOPXJXkaIr4OyeorzfrNgW9ZGBi+JvPDa/j9/T6GB9CgjlB1AN9+CCM/6n2ru2yNOWMb80i8AIf7frBIsCE5mBvpZ+sikhsTBQRcvk/YnR25DrXAkaMZKn5ZjpH6wZElGuoGKWkvt7GX/Nvu+quY7q/bbY0UYrJXFPZS1CxtWoLNvOIouGchmVYrzViAmFcPPHphfW5pqwITdXZ2dan5VB4Noj5vmfASJIpzWHUDIKypkwyWJ7roC/vGOAVMwThZej9ovv9x3l9Mw7mh/GqoT8E13dRLgNYlI2cea9FVat/RrfvnMItD2+bITgPhAYWlwxgdizgHlufHV8v+Y8a+pmz/Jo2aJAbX06gkxWNVHXSixV4SMvP1isXmILT1eQeP3vL9GwUEM7AY0S7S88ON/rlMXyXM/f8rP0tBagnvdZjhMyrUBj7V3L+kvEnI9qwtdbEj/MP/xhGhu30fnxkL+nQMKkz6eC3ipVvg+pbazjWasl6BTObzkRwrnAbhRWXDcA9tLXt3XXOYCGXXOXwRZyhdOL3NYzwBAxEq0nL1pkO2llOXyrrl+0hrK/vG2TYgaitf53vIfIfw1ugdIFVFNohnN+XTjUrxEe/dfu9Dr7Ay9j83S5CPle2OHPpTaUTrTUotiIhMdOeQ81ld4e/PiAA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
